### PR TITLE
Ray 220 update

### PR DESCRIPTION
**Pull request by npanpaliya**
## Checklist before submitting

- [ ] Did you read the [contributor guide](https://github.com/open-ce/open-ce/blob/main/CONTRIBUTING.md)?
- [ ] Did you update any affected [documentation](https://github.com/open-ce/open-ce/blob/main/doc/)?
- [ ] Did you write any tests to validate this change?

## Description

Fixes # (issue).

## Review process to land 

1. All tests and other checks must succeed.
2. At least one [maintainer](https://github.com/open-ce/open-ce/blob/main/MAINTAINERS.md) must review and approve.
3. If any  [maintainer](https://github.com/open-ce/open-ce/blob/main/MAINTAINERS.md) requests changes, they must be addressed.

### CODE REVIEW

**Review by alexlang74 — APPROVED** [review]
Caveat: I can't say that I understand in depth what's happening here.-)

**Comment by npanpaliya** [comment]
> Caveat: I can't say that I understand in depth what's happening here.-)

I'll explain it in our next call.

**Comment by npanpaliya** [comment]
@alexlang74 @cdeepali - Please let me know if you want me to walk through these changes in our call.

**Comment by alexlang74** [comment]
Sure - when we're through with scrum and have time left, we can do this today!

**Pull request merged**
